Repository PaddlePaddle/FastDeploy, pull requests merged in 2025-09, with the labels that each got.

#3714 Add CI cases
  tests/ci_use/EB_Lite/test_EB_Lite_serving.py
  tests/ci_use/EB_Lite/test_ernie_21b_mtp.py
Labels: contributor

#3749 add ci images build job
  .github/workflows/_accuracy_test.yml
  .github/workflows/_base_test.yml
  .github/workflows/_ci_image_build.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_stable_test.yml
  .github/workflows/_unit_test_coverage.yml
  .github/workflows/ci_image_update.yml
  .github/workflows/pr_build_and_test.yml
  .github/workflows/publish_job.yml
  scripts/unittest_requirement.txt
  tools/dockerfile/Dockerfile.ci
  tools/dockerfile/docker_build.sh
  tools/dockerfile/requirements.txt
Labels: contributor

#3783 Update test_ernie_21b_mtp.py
  tests/ci_use/EB_Lite/test_ernie_21b_mtp.py
Labels: contributor

#3777 fix ce build job
  .github/workflows/ce_job.yml
Labels: contributor

#3735 rename speculate_token_penalty_multi_scores.cu
  custom_ops/gpu_ops/speculate_decoding/speculate_get_token_penalty_multi_scores.cu
Labels: contributor, HappyOpenSource

#3752 rename fused_get_rope.cu
  custom_ops/gpu_ops/cpp_extensions.cc
  custom_ops/gpu_ops/fused_get_rotary_embedding.cu
  custom_ops/gpu_ops/moe/moe_expert_ffn_wint2.cu
  custom_ops/gpu_ops/moe/winx_unzip.cu
  custom_ops/gpu_ops/set_value_by_flags_and_idx.cu
  custom_ops/gpu_ops/speculate_decoding/speculate_set_value_by_flags_and_idx.cu
  custom_ops/setup_ops.py
  fastdeploy/model_executor/models/deepseek_v3.py
  fastdeploy/model_executor/models/ernie4_5_moe.py
  fastdeploy/model_executor/models/ernie4_5_vl/ernie4_5_vl_moe.py
  fastdeploy/model_executor/models/qwen2.py
  fastdeploy/model_executor/models/qwen3.py
  fastdeploy/model_executor/models/qwen3moe.py
  tests/graph_optimization/test_cuda_graph_dynamic_subgraph.py
  tests/graph_optimization/test_cuda_graph_recapture.py
  tests/graph_optimization/test_cuda_graph_spec_decode.py
  tests/graph_optimization/test_static_graph_cuda_graph_split.py
Labels: contributor, HappyOpenSource

#3570 【Hackathon 9th No.84】Supplementary Unit Test for fastdeploy/reasoning
  tests/reasoning/test_reasoning_parser.py
Labels: contributor, PaddlePaddle Hackathon

#3733 fix w8a8.py
  fastdeploy/model_executor/layers/quantization/w8a8.py
Labels: contributor, skip-ci: coverage, HappyOpenSource

#3734 fix dcu_worker.py
  fastdeploy/worker/dcu_worker.py
Labels: contributor, skip-ci: coverage, HappyOpenSource

#3829 [XPU] FIX XPU CI BUG
  scripts/run_ci_xpu.sh
Labels: contributor

#3819 [Doc] update wint2 doc
  docs/quantization/wint2.md
  docs/quantization/wint2.png
  docs/zh/quantization/wint2.md
  docs/zh/quantization/wint2.png
Labels: skip-ci: coverage

#3844 [XPU]Update XPU CI Case
  .github/workflows/ci_xpu.yml
  scripts/run_ci_xpu.sh
Labels: contributor

#3856 [Feature] add HTTP GET retry
  fastdeploy/entrypoints/chat_utils.py
Labels: contributor

#3855 [XPU] Update XPU stable xvllm and xtdk version for 2.2 & Change CI Case
  custom_ops/xpu_ops/src/download_dependencies.sh
  scripts/run_ci_xpu.sh
Labels: contributor

#3730 【Hackathon 9th No.43、45】add speculate_get_padding_offset
  tests/operators/test_speculate_get_padding_offset.py
  tests/operators/test_speculate_get_seq_lens_output.py
Labels: contributor, PaddlePaddle Hackathon

#3740 【Hackathon 9th No.42】add test_speculate_get_output_padding_offset
  tests/operators/test_speculate_get_output_padding_offset.py
Labels: contributor, PaddlePaddle Hackathon

#3853 [XPU] Update XPU stable xvllm and xtdk version for 2.2
  custom_ops/xpu_ops/src/download_dependencies.sh
  scripts/run_ci_xpu.sh
Labels: contributor

#3870 Support for async processor added.
  fastdeploy/entrypoints/engine_client.py
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
  tests/utils/test_custom_chat_template.py
Labels: contributor

#3841 fix typo EngineSevice EngineService
  fastdeploy/engine/common_engine.py
  fastdeploy/engine/engine.py
  fastdeploy/engine/expert_service.py
Labels: contributor, HappyOpenSource

#3708 【Hackathon 9th No.27】add test_get_padding_offset
  tests/operators/test_get_padding_offset.py
Labels: contributor, PaddlePaddle Hackathon

#3746 【Hackathon 9th No.54、57】 add unit tests for per_token_quant and per_token_quant_padding
  tests/operators/test_per_token_quant.py
Labels: contributor, PaddlePaddle Hackathon

#3885 Update test_ernie_21b_mtp.py
  tests/ci_use/EB_Lite/test_ernie_21b_mtp.py
Labels: contributor

#3894 [Fix] fix qwen_vl_processor miss image_patch_id
  fastdeploy/input/qwen_vl_processor/qwen_vl_processor.py
Labels: contributor

#3748 【Hackathon 9th No.32】add unit tests for group_swiglu_with_masked
  tests/operators/test_group_swiglu_with_masked.py
Labels: contributor, PaddlePaddle Hackathon

#3915 Update requirements.txt
  requirements.txt
Labels: contributor

#3797 [fix]load hadamard_block_size from config
  custom_ops/gpu_ops/cpp_extensions.cc
  custom_ops/gpu_ops/moe/fast_hardamard_kernel.cu
  custom_ops/gpu_ops/moe/fast_hardamard_kernel.h
  custom_ops/gpu_ops/moe/moe_ffn.cu
  fastdeploy/engine/engine.py
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
  fastdeploy/model_executor/layers/quantization/mix_quant.py
  fastdeploy/model_executor/layers/quantization/w4a8.py
  fastdeploy/model_executor/layers/quantization/w4afp8.py
  tests/model_loader/test_w4a8_model.py
Labels: skip-ci: coverage

#3898 [Feature] support controller port in multi api server
  fastdeploy/entrypoints/openai/multi_api_server.py
Labels: skip-ci: coverage

#3920 [BugFix] qwen2.5vl enable_thinking=true bug fix
  fastdeploy/input/qwen_vl_processor/qwen_vl_processor.py
Labels: contributor

#3838 [Feature] add HTTP GET retry
  fastdeploy/entrypoints/chat_utils.py
Labels: contributor

#3897 [XPU]Fixed the issue of performance degradation caused by enabling ENABLE_V1_KVCACHE_SCHEDULER
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
  fastdeploy/engine/sched/resource_manager_v1.py
  fastdeploy/worker/xpu_model_runner.py
Labels: skip-ci: coverage

#3459 [Excutor] Experiment Feature-Support Prefill in cudagraph
  custom_ops/gpu_ops/append_attn/append_attention_c16_impl.cuh
  custom_ops/gpu_ops/append_attn/append_attention_c4_impl.cuh
  custom_ops/gpu_ops/append_attn/append_attention_c8_impl.cuh
  custom_ops/gpu_ops/append_attn/get_block_shape_and_split_kv_block.cu
  custom_ops/gpu_ops/cpp_extensions.cc
  fastdeploy/config.py
  fastdeploy/model_executor/forward_meta.py
  fastdeploy/model_executor/layers/attention/append_attn_backend.py
  fastdeploy/model_executor/layers/attention/flash_attn_backend.py
  fastdeploy/model_executor/layers/attention/mla_attention_backend.py
  fastdeploy/model_executor/layers/attention/ops/get_block_shape_and_split_kv_block.py
  fastdeploy/spec_decode/mtp.py
  fastdeploy/worker/gcu_model_runner.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/worker_process.py
  tests/graph_optimization/test_cuda_graph_dynamic_subgraph.py
  tests/graph_optimization/test_cuda_graph_spec_decode.py
  tests/graph_optimization/test_static_graph_cuda_graph_split.py
  tests/layers/test_append_attention.py
  tests/layers/test_append_attention_with_output.py
  tests/operators/test_tree_mask.py
Labels: contributor

#3932 [BugFix] fix default parser
  fastdeploy/input/preprocess.py
Labels: contributor

#3938 rename ep_moe_prefill_func ep_moe_expert_dispatch
  custom_ops/gpu_ops/moe/ep_moe_expert_dispatch.cu
Labels: contributor, HappyOpenSource

#3896 Modify markdown
  docs/online_serving/graceful_shutdown_service.md
  docs/online_serving/images/graceful_shutdown.png
  docs/zh/online_serving/graceful_shutdown_service.md
  docs/zh/online_serving/images/graceful_shutdown.png
  mkdocs.yml
Labels: contributor

#3744 【Hackathon 9th No.22】add unit tests for share_external_data
  tests/operators/test_share_external_data.py
Labels: contributor, PaddlePaddle Hackathon

#3732 【Hackathon 9th No.68】supplementary unit test for ngram_match
  tests/operators/test_ngram_match.py
Labels: contributor, PaddlePaddle Hackathon

#3742 【Hackathon 9th No.44】add test_speculate_get_token_penalty_multi_scores.py
  tests/operators/test_speculate_get_token_penalty_multi_scores.py
Labels: contributor, PaddlePaddle Hackathon

#3832 【Hackathon 9th No.69】add test_draft_model_preprocess
  tests/operators/test_draft_model_preprocess.py
Labels: contributor, PaddlePaddle Hackathon

#3941 【Hackathon 9th No.66】add test_speculate_set_stop_value_multi_seqs
  tests/operators/test_speculate_set_stop_value_multi_seqs.py
Labels: contributor, PaddlePaddle Hackathon

#3862 【Hackathon 9th No.36】add test_extract_text_token_output
  tests/operators/test_extract_text_token_output.py
Labels: contributor, PaddlePaddle Hackathon

#3962 [CI] update ci
  scripts/run_pre_ce.sh
  tests/ce/deploy/deploy.py
  tests/cov_pytest.ini
  tests/model_loader/utils.py
Labels: contributor

#3972 [Optimize]Error messages about Model api.
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
  tests/entrypoints/openai/test_serving_models.py
Labels: contributor

#4007 metrics shared folder naming
  fastdeploy/metrics/metrics.py
Labels: contributor

#4010 Fixed the issue of metrics file conflicts between multiple instances …
  fastdeploy/metrics/metrics.py
Labels: contributor

#3935 【Hackathon 9th No.28】add test_cutlass_fp8_fp8_fp8_dual_gemm_fused
  tests/operators/test_cutlass_fp8_fp8_fp8_dual_gemm_fused.py
Labels: contributor, PaddlePaddle Hackathon

#4025 Use uuid to name the metrics shared folder
  fastdeploy/metrics/metrics.py
  tests/metrics/test_metrics.py
Labels: contributor

#4023 [Fix] fix multi api server log dir
  fastdeploy/entrypoints/openai/multi_api_server.py
Labels: skip-ci: coverage

#3967 [Fix] fix multi api server log dir
  fastdeploy/entrypoints/openai/multi_api_server.py
Labels: skip-ci: coverage

#4071 Support offline inference with streaming output
  fastdeploy/entrypoints/llm.py
  tests/ci_use/Qwen2-7B-Instruct_offline/test_Qwen2-7B-Instruct_offline.py
Labels: contributor

#4044 【FastDeploy CLI】collect-env subcommand
  docs/online_serving/metrics.md
  docs/zh/online_serving/metrics.md
  fastdeploy/collect_env.py
  fastdeploy/entrypoints/cli/collect_env.py
  tests/entrypoints/cli/test_collect_env_conmmand.py
  tests/entrypoints/cli/test_collect_env_script.py
Labels: contributor

#4036 [v1 loader]qwen Offline fp8
  fastdeploy/model_executor/layers/linear.py
  fastdeploy/model_executor/layers/lm_head.py
  fastdeploy/model_executor/layers/moe/fused_moe_backend_base.py
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_deepgemm_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_triton_backend.py
  fastdeploy/model_executor/layers/moe/moe.py
  fastdeploy/model_executor/layers/quantization/__init__.py
  fastdeploy/model_executor/layers/quantization/block_wise_fp8.py
  fastdeploy/model_executor/layers/quantization/mix_quant.py
  fastdeploy/model_executor/layers/quantization/weight_only.py
  fastdeploy/model_executor/layers/quantization/wfp8afp8.py
  fastdeploy/model_executor/load_weight_utils.py
  fastdeploy/model_executor/models/ernie4_5_moe.py
  fastdeploy/model_executor/models/ernie4_5_vl/dfnrope/modeling.py
  fastdeploy/model_executor/models/ernie4_5_vl/modeling_resampler.py
  fastdeploy/model_executor/utils.py
  fastdeploy/worker/worker_process.py
  tests/conftest.py
  tests/model_loader/test_offline_model.py
  tests/model_loader/utils.py
Labels: skip-ci: coverage

#4099 [MTP]Develop mtp reshard
  fastdeploy/config.py
  fastdeploy/multimodal/registry.py
  fastdeploy/rl/rollout_config.py
Labels: skip-ci: coverage

#4091 [feat] support prefix cache clearing when `/clear_load_weight` is called
  custom_ops/gpu_ops/unset_data_ipc.cu
  custom_ops/setup_ops.py
  fastdeploy/cache_manager/cache_messager.py
  fastdeploy/cache_manager/cache_transfer_manager.py
  fastdeploy/cache_manager/prefix_cache_manager.py
  fastdeploy/engine/args_utils.py
  fastdeploy/engine/common_engine.py
  fastdeploy/engine/engine.py
  fastdeploy/engine/expert_service.py
  fastdeploy/entrypoints/engine_client.py
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/envs.py
  fastdeploy/inter_communicator/__init__.py
  fastdeploy/inter_communicator/ipc_signal_const.py
  fastdeploy/rl/dynamic_weight_manager.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/worker_process.py
Labels: skip-ci: coverage

#4135 [Doc][CE]x1_a3b server config
  benchmarks/yaml/x1-a3b-128k-wint8-h800-tp1.yaml
Labels: contributor

#4098 ci: Increase compilation task time limit
  .github/workflows/_build_linux.yml
  .github/workflows/_ci_image_build.yml
  .github/workflows/_unit_test_coverage.yml
  tools/dockerfile/Dockerfile.ci
  tools/dockerfile/requirements_paddle_nv.txt
Labels: contributor

#4116 [FDConfig]Remove max_num_batched_tokens/max_num_seqs in parallel config
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
  fastdeploy/engine/common_engine.py
  fastdeploy/engine/engine.py
  fastdeploy/engine/sched/resource_manager_v1.py
  fastdeploy/model_executor/guided_decoding/xgrammar_backend.py
  fastdeploy/model_executor/layers/attention/attention.py
  fastdeploy/model_executor/layers/attention/flash_attn_backend.py
  fastdeploy/model_executor/layers/attention/moba_attention_backend.py
  fastdeploy/model_executor/layers/backends/gcu/attention/flash_attn_backend.py
  fastdeploy/model_executor/layers/backends/gcu/attention/mem_efficient_attn_backend.py
  fastdeploy/model_executor/layers/sample/sampler.py
  fastdeploy/model_executor/models/deepseek_v3.py
  fastdeploy/scheduler/config.py
  fastdeploy/spec_decode/base.py
  fastdeploy/worker/gcu_model_runner.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/metax_model_runner.py
  fastdeploy/worker/model_runner_base.py
  fastdeploy/worker/worker_process.py
  fastdeploy/worker/xpu_model_runner.py
  tests/graph_optimization/test_cuda_graph_dynamic_subgraph.py
  tests/graph_optimization/test_cuda_graph_recapture.py
  tests/graph_optimization/test_cuda_graph_spec_decode.py
  tests/graph_optimization/test_graph_opt_backend.py
  tests/graph_optimization/test_static_graph_cuda_graph_split.py
  tests/utils.py
  tests/utils/test_config.py
  tests/v1/test_prefix_cache.py
  tests/v1/test_schedule_output.py
Labels: skip-ci: coverage

#4039 [NewFeture]add ep rollout model init and update/clear ep buffer
  custom_ops/gpu_ops/moe/ep_moe_expert_dispatch.cu
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
  fastdeploy/model_executor/layers/moe/ep.py
  fastdeploy/model_executor/layers/moe/fused_moe_backend_base.py
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_deepgemm_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_marlin_backend.py
  fastdeploy/rl/dynamic_weight_manager.py
  fastdeploy/rl/rollout_config.py
  fastdeploy/worker/worker_process.py
  tests/utils/test_config.py
Labels: skip-ci: coverage

#4113 Add param valid log
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
  fastdeploy/utils.py
Labels: contributor, skip-ci: coverage

#4153 [Cherry-pick] fix MTP load with v1 loader
  fastdeploy/model_executor/models/ernie4_5_mtp.py
Labels: skip-ci: coverage

#4159 [FastDeploy CLI]collect-env unitest bug fix
  tests/entrypoints/cli/test_collect_env_script.py
Labels: contributor

#4145 optimize dy_cfp8's performance
  custom_ops/gpu_ops/append_attn/append_attention_c8_impl.cuh
  custom_ops/gpu_ops/append_attn/append_attention_func.cuh
Labels: skip-ci: coverage

#4151 [Logprob] EP support logprob
  custom_ops/gpu_ops/get_output_msg_with_topk.cc
  fastdeploy/engine/args_utils.py
  fastdeploy/output/token_processor.py
Labels: skip-ci: coverage

#4191 fix nul
  tools/codestyle/pre_commit.sh
Labels: contributor

#4176 fix typos
  benchmarks/benchmark_mtp.py
  custom_ops/gpu_ops/custom_all_reduce/all_reduce.cuh
  docs/get_started/installation/nvidia_gpu.md
  docs/usage/code_overview.md
  docs/usage/log.md
  mkdocs.yml
  tests/ce/server/test_return_token_ids.py
  tests/ci_use/EB_Lite_with_adapter/zmq_client.py
  tests/distributed/custom_all_reduce.py
  tools/deep_gemm_pre-compile/pre_compile.py
Labels: contributor, HappyOpenSource

#4046 【Hackathon 9th No.40】add test_top_p_candidates
  tests/operators/test_top_p_candidates.py
Labels: contributor, PaddlePaddle Hackathon

#3651 [Iluvatar GPU] Optimize attention performance and fix moe load ckpt e…
  .github/workflows/ci_iluvatar.yml
  custom_ops/gpu_ops/helper.h
  custom_ops/iluvatar_ops/mixed_fused_attn.cu
  custom_ops/iluvatar_ops/moe_dispatch.cu
  custom_ops/iluvatar_ops/paged_attn.cu
  custom_ops/iluvatar_ops/prefill_fused_attn.cu
  custom_ops/setup_ops.py
  docs/get_started/installation/iluvatar_gpu.md
  docs/zh/get_started/installation/iluvatar_gpu.md
  fastdeploy/config.py
  fastdeploy/model_executor/layers/attention/iluvatar_attn_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
  fastdeploy/model_executor/models/ernie4_5_moe.py
  fastdeploy/model_executor/ops/iluvatar/__init__.py
  fastdeploy/model_executor/ops/iluvatar/paged_attention.py
  scripts/run_ci_iluvatar.sh
  tests/ci_use/iluvatar_UT/run_ernie300B_4layer.py
Labels: contributor, skip-ci: coverage

#4213 [XPU] Enable XPU V1 mode based on environment variable
  custom_ops/xpu_ops/src/ops/moe_expert_ffn.cc
  fastdeploy/engine/args_utils.py
  fastdeploy/worker/worker_process.py
  scripts/run_ci_xpu.sh
Labels: contributor

#4107 【Hackathon 9th No.24】add rebuild_padding
  tests/operators/test_rebuild_padding.py
Labels: contributor, PaddlePaddle Hackathon

#4167 [Bug Fix] disable prefix caching in mm model
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
Labels: contributor

#4241 [Fix] X1 reasoning parser ， skip parsing of `\n` around special tokens
  fastdeploy/entrypoints/openai/tool_parsers/ernie_x1_tool_parser.py
  fastdeploy/reasoning/ernie_x1_reasoning_parsers.py
  tests/entrypoints/openai/tool_parsers/test_ernie_x1_tool_parser.py
  tests/reasoning/test_reasoning_parser.py
Labels: contributor

#4087 [Model] Qwen2.5VL support --use-cudagraph and unit testing
  docs/offline_inference.md
  docs/zh/offline_inference.md
  fastdeploy/model_executor/models/qwen2_5_vl/qwen2_5_vl.py
  tests/ci_use/Qwen2_5_VL/test_Qwen2_5_VL_serving.py
  tests/e2e/test_Qwen2_5_VL_serving.py
Labels: contributor

#4237 Add cli run batch
  fastdeploy/entrypoints/cli/main.py
  fastdeploy/entrypoints/cli/run_batch.py
  fastdeploy/entrypoints/openai/protocol.py
  fastdeploy/entrypoints/openai/run_batch.py
  fastdeploy/utils.py
  tests/entrypoints/openai/test_run_batch.py
  tests/entrypoints/openai/test_run_batch_proto.py
  tests/entrypoints/openai/test_run_batch_subcommand.py
  tests/utils/test_run_batch_tools.py
Labels: contributor

#4266 [XPU] fix VL thinking mode
  fastdeploy/worker/xpu_model_runner.py
Labels: XPU

#4312 [BugFix]remove redundant includes
  custom_ops/gpu_ops/ipc_sent_key_value_cache_by_remote_ptr.cu
Labels: contributor, HappyOpenSource
