Repository PaddlePaddle/FastDeploy, pull requests merged in 2025-08, with the labels that each got.

#3141 fix ci
  .github/workflows/_unit_test_coverage.yml
  scripts/coverage_run.sh
Labels: contributor

#3163 Update __init__.py
  test/ce/server/core/__init__.py
Labels: contributor

#3147 [XPU] Update XPU dockerflie
  dockerfiles/Dockerfile.xpu
Labels: contributor

#3191 [CI] add test_compare_top_logprobs
  test/ce/server/test_compare_top_logprobs.py
  tools/codestyle/pre_commit.sh
Labels: contributor

#3203 Add more base chat cases
  test/ce/server/core/__init__.py
  test/ce/server/core/utils.py
  test/ce/server/test_base_chat.py
Labels: contributor

#3201 [Bugfix] Fix uninitialized decoded_token and add corresponding unit test
  fastdeploy/entrypoints/llm.py
  test/ce/server/test_base_chat.py
  test/entrypoints/openai/test_build_sample_logprobs.py
Labels: contributor

#3229 [CI] Add ci case for min token and max token
  test/ce/server/test_params_boundary.py
Labels: contributor

#3125 [Feature] multi source download
  fastdeploy/utils.py
  requirements.txt
  scripts/coverage_run.sh
  test/utils/test_download.py
Labels: contributor

#3247 [fix] fix completion stream api output_tokens not in usage
  fastdeploy/entrypoints/openai/serving_completion.py
Labels: contributor

#3253 [Trace]merge develop trace FD_START
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/envs.py
  fastdeploy/metrics/trace_util.py
Labels: contributor

#3260 [Trace]merge develop trace FD_START
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/envs.py
  fastdeploy/metrics/trace_util.py
Labels: contributor

#3234 [Iluvatar GPU] Optimze attention and moe performance
  .github/workflows/ci_gcu.yml
  .github/workflows/ci_iluvatar.yml
  custom_ops/gpu_ops/sample_kernels/rejection_top_p_sampling.cu
  custom_ops/gpu_ops/sample_kernels/sampling.cuh
  custom_ops/gpu_ops/sample_kernels/utils.cuh
  custom_ops/iluvatar_ops/paged_attn.cu
  custom_ops/iluvatar_ops/runtime/iluvatar_context.h
  custom_ops/iluvatar_ops/w8a16_group_gemm.cu
  custom_ops/setup_ops.py
  docs/get_started/installation/iluvatar_gpu.md
  fastdeploy/config.py
  fastdeploy/engine/engine.py
  fastdeploy/model_executor/layers/attention/iluvatar_attn_backend.py
  fastdeploy/model_executor/layers/sample/ops/top_k_top_p_sampling.py
  fastdeploy/model_executor/ops/iluvatar/moe_ops.py
  fastdeploy/model_executor/ops/iluvatar/paged_attention.py
  fastdeploy/model_executor/pre_and_post_process.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/iluvatar_model_runner.py
  fastdeploy/worker/iluvatar_worker.py
  fastdeploy/worker/worker_process.py
  requirements_iluvatar.txt
  scripts/run_ci_iluvatar.sh
  test/ci_use/iluvatar_UT/run_ernie300B_4layer.py
Labels: contributor

#3189 [CI] add CI logprobs case
  test/ce/server/test_logprobs.py
  test/ce/server/test_stream.py
Labels: contributor

#3225 add base test ci
  .github/workflows/_base_test.yml
  .github/workflows/_clone_linux.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/pr_build_and_test.yml
  test/ce/deploy/deploy.py
Labels: contributor

#3223 [Excutor] Fixed the issue of CUDA graph execution failure caused by different branches during decoding
  custom_ops/gpu_ops/append_attn/append_attention_c16_impl.cuh
  custom_ops/gpu_ops/append_attn/append_attention_c4_impl.cuh
  custom_ops/gpu_ops/append_attn/append_attention_c8_impl.cuh
Labels: contributor

#3298 Update _base_test.yml
  .github/workflows/_base_test.yml
Labels: contributor

#3299 Update _base_test.yml
  .github/workflows/_base_test.yml
Labels: contributor

#3356 Completion add raw_prediction/text_after_process
  fastdeploy/entrypoints/openai/protocol.py
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
  fastdeploy/input/ernie_processor.py
  fastdeploy/input/ernie_vl_processor.py
  fastdeploy/input/mm_processor/process.py
  fastdeploy/input/text_processor.py
Labels: contributor

#3361 Release/2.1
  fastdeploy/entrypoints/openai/serving_completion.py
  test/entrypoints/openai/test_serving_completion.py
Labels: contributor

#3352 Use latest PaddlePaddle package (#3347)
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_unit_test_coverage.yml
  .github/workflows/ci.yml
Labels: contributor

#3241 [MetaxGPU] Support FastDeploy on metax gpu
  build.sh
  custom_ops/gpu_ops/helper.h
  custom_ops/setup_ops.py
  fastdeploy/model_executor/forward_meta.py
  fastdeploy/model_executor/layers/activation.py
  fastdeploy/model_executor/layers/attention/base_attention_backend.py
  fastdeploy/model_executor/layers/backends/__init__.py
  fastdeploy/model_executor/layers/backends/metax/__init__.py
  fastdeploy/model_executor/layers/backends/metax/attention/__init__.py
  fastdeploy/model_executor/layers/backends/metax/attention/flash_attention_interface.py
  fastdeploy/model_executor/layers/backends/metax/attention/flash_attn_backend.py
  fastdeploy/model_executor/layers/backends/metax/moe/__init__.py
  fastdeploy/model_executor/layers/backends/metax/moe/fused_moe_triton_metax_backend.py
  fastdeploy/model_executor/layers/backends/metax/moe/triton_moe_kernels.py
  fastdeploy/model_executor/layers/linear.py
  fastdeploy/model_executor/layers/moe/moe.py
  fastdeploy/model_executor/layers/quantization/weight_only.py
  fastdeploy/model_executor/layers/rotary_embedding.py
  fastdeploy/model_executor/layers/sample/ops/apply_penalty_multi_scores.py
  fastdeploy/model_executor/layers/sample/sampler.py
  fastdeploy/model_executor/pre_and_post_process.py
  fastdeploy/platforms/__init__.py
  fastdeploy/platforms/base.py
  fastdeploy/platforms/maca.py
  fastdeploy/worker/metax_model_runner.py
  fastdeploy/worker/metax_worker.py
  fastdeploy/worker/worker_process.py
  requirements_metaxgpu.txt
  setup.py
Labels: contributor

#3368 fix TestOpenAIServingCompletion fail
  test/entrypoints/openai/test_serving_completion.py
Labels: contributor

#3371 Optimize CI execution workflow
  .github/workflows/_base_test.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_unit_test_coverage.yml
  scripts/coverage_run.sh
Labels: contributor

#3392 feat(log):add_request_and_response_log
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
Labels: contributor

#3384 Optimize CI execution workflow. (#3371)
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_unit_test_coverage.yml
  scripts/coverage_run.sh
Labels: contributor

#3350 Add requirements for running unit tests
  .github/workflows/_unit_test_coverage.yml
  scripts/unittest_requirement.txt
Labels: contributor

#3400 [BugFix] fix ErnieProcessor not set raw_prediction
  fastdeploy/input/ernie_processor.py
  test/input/test_ernie_processor.py
Labels: contributor

#3401 [BugFix] fix ErnieProcessor not set raw_prediction
  fastdeploy/input/ernie_processor.py
  test/input/test_ernie_processor.py
Labels: contributor

#3391 feat(log):add_request_and_response_log
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
Labels: contributor

#3359 【CI】 evil case
  test/ce/server/test_evil_cases.py
Labels: contributor

#3411 [CI] fix run_ci error in release/2.0.4
  .github/workflows/ci.yml
  scripts/run_ci.sh
  test/ci_use/EB_Lite/test_EB_Lite_serving.py
  test/ci_use/EB_VL_Lite/test_EB_VL_Lite_serving.py
Labels: contributor

#3351 [Bugs] Fix DeepGEMM pre-compile tools.
  tools/deep_gemm_pre-compile/README.md
  tools/deep_gemm_pre-compile/generate_config.py
  tools/deep_gemm_pre-compile/pre_compile.py
  tools/deep_gemm_pre-compile/pre_compile.sh
Labels: contributor

#3389 add accuracy check ci
  .github/workflows/_accuracy_test.yml
  .github/workflows/pr_build_and_test.yml
  test/ce/accuracy_cases/gsm8k.py
  test/ce/server/gsm8k.parquet
  test/ce/server/gsm8k.py
Labels: contributor

#3245 【BugFix】completion接口echo回显支持
  fastdeploy/entrypoints/openai/serving_completion.py
  test/entrypoints/openai/test_completion_echo.py
  test/entrypoints/openai/test_serving_completion.py
Labels: contributor

#3482 [bigfix] temporarily lock the paddlepaddle-gpu==3.0.0.dev20250818
  .github/workflows/_accuracy_test.yml
  .github/workflows/_base_test.yml
  .github/workflows/_build_linux.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_stable_test.yml
  .github/workflows/_unit_test_coverage.yml
  scripts/run_unittest.sh
Labels: contributor

#3495 Update disaggregated.md
  docs/zh/features/disaggregated.md
Labels: contributor

#3499 [CI] fix run_ci error in release/2.1
  .github/workflows/_build_linux.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_unit_test_coverage.yml
  scripts/run_unittest.sh
Labels: contributor

#3481 [XPU] Cherry-pick Commit Release2.1 44c0c7e into develop
  fastdeploy/worker/xpu_model_runner.py
  fastdeploy/worker/xpu_worker.py
Labels: contributor

#3519 Update ci
  tests/ce/server/test_seed_usage.py
  tests/ci_use/ERNIE_0dot3B/test_ernie_03b_pd.py
Labels: contributor

#3526 [CI] add container naming and cleanup logic in workflows
  .github/workflows/_accuracy_test.yml
  .github/workflows/_base_test.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_stable_test.yml
  .github/workflows/_unit_test_coverage.yml
Labels: contributor

#3535 [CI] fix xpu ci bug
  scripts/run_ci_xpu.sh
Labels: contributor

#3563 [Bug Fix] Close get think_end_id for XPU for now.
  fastdeploy/worker/worker_process.py
Labels: contributor

#3579 [CI] add sot test
  .github/workflows/_base_test.yml
  tests/ce/deploy/21b_sot.yaml
Labels: contributor

#3573 Modify the existing coverage collection method
  .github/workflows/_unit_test_coverage.yml
  scripts/.coveragerc
  scripts/coverage_run.sh
  tests/cov_pytest.ini
Labels: contributor

#3553 Add coverage skip
  .github/workflows/_unit_test_coverage.yml
  .github/workflows/check-bypass.yml
  .github/workflows/pr_build_and_test.yml
Labels: contributor

#3586 [CI] temporarily disable sot test due to occasional timeout issue
  .github/workflows/_base_test.yml
Labels: contributor

#3600 [fix] fix ZmqIpcClient.close() error
  fastdeploy/engine/engine.py
  fastdeploy/inter_communicator/zmq_client.py
  fastdeploy/inter_communicator/zmq_server.py
Labels: contributor

#3608 [Feature] bad words support v1 scheduler and specifiy token ids
  docs/features/sampling.md
  docs/online_serving/README.md
  docs/zh/features/sampling.md
  docs/zh/online_serving/README.md
  fastdeploy/engine/engine.py
  fastdeploy/engine/sampling_params.py
  fastdeploy/entrypoints/openai/protocol.py
  fastdeploy/input/ernie_processor.py
  fastdeploy/input/ernie_vl_processor.py
  fastdeploy/input/qwen_vl_processor.py
  fastdeploy/input/text_processor.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/metax_model_runner.py
  fastdeploy/worker/xpu_model_runner.py
  tests/ci_use/EB_Lite/test_EB_Lite_serving.py
  tests/e2e/test_EB_Lite_serving.py
Labels: skip-ci: coverage

#3591 【Inference Optimize】Support DSK qkv_a_proj horizontal fusion under V0 Loder
  fastdeploy/model_executor/layers/linear.py
  fastdeploy/model_executor/models/deepseek_v3.py
Labels: skip-ci: coverage

#3616 [CUDAGraph]Add debug func
  fastdeploy/model_executor/graph_optimization/cudagraph_piecewise_backend.py
Labels: skip-ci: coverage

#3620 [Bugfix] Correct logprobs aggregation for multiple prompts in /completions endpoint
  fastdeploy/entrypoints/openai/serving_completion.py
Labels: contributor

#3618 [Bugfix] Correct logprobs aggregation for multiple prompts in /completions endpoint
  fastdeploy/entrypoints/openai/serving_completion.py
Labels: contributor

#3598 [NewFeature]Support dp multi api server && Fix some bug in mixed ep && merge develop
  custom_ops/gpu_ops/moe/ep_moe_prefill_func.cu
  fastdeploy/cache_manager/cache_messager.py
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
  fastdeploy/engine/common_engine.py
  fastdeploy/engine/engine.py
  fastdeploy/engine/expert_service.py
  fastdeploy/entrypoints/engine_client.py
  fastdeploy/entrypoints/openai/api_server.py
  fastdeploy/entrypoints/openai/multi_api_server.py
  fastdeploy/entrypoints/openai/serving_chat.py
  fastdeploy/entrypoints/openai/serving_completion.py
  fastdeploy/entrypoints/openai/utils.py
  fastdeploy/envs.py
  fastdeploy/inter_communicator/__init__.py
  fastdeploy/inter_communicator/ipc_signal.py
  fastdeploy/inter_communicator/zmq_client.py
  fastdeploy/model_executor/layers/moe/ep.py
  fastdeploy/splitwise/splitwise_connector.py
  fastdeploy/utils.py
  fastdeploy/worker/gcu_model_runner.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/worker_process.py
  scripts/run_ci_xpu.sh
Labels: skip-ci: coverage

#3209 [Feature] block sparse attention
  custom_ops/gpu_ops/cpp_extensions.cc
  custom_ops/gpu_ops/moba_attn/moba_attn.cu
  custom_ops/gpu_ops/moba_attn/moba_attn.h
  custom_ops/gpu_ops/moba_attn/moba_attn_utils.hpp
  custom_ops/gpu_ops/moba_attn/moba_decoder_attn/moba_decoder_attn.cu
  custom_ops/gpu_ops/moba_attn/moba_decoder_attn/moba_decoder_attn_kernel.h
  custom_ops/gpu_ops/moba_attn/moba_decoder_attn/moba_decoder_write_cache.cu
  custom_ops/gpu_ops/moba_attn/moba_decoder_attn/moba_qk_sort_decoder.cu
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/kernel_traits.h
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/mainloop_attn.hpp
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/moba_encoder_attn.cu
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/moba_encoder_write_cache.cu
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/moba_qk_sort_encoder.cu
  custom_ops/gpu_ops/moba_attn/moba_encoder_attn/softmax.hpp
  custom_ops/gpu_ops/moba_attn/moba_process/moba_get_kv_from_cache.cu
  custom_ops/gpu_ops/moba_attn/moba_process/moba_mlp_einsum.cu
  custom_ops/gpu_ops/moba_attn/moba_process/moba_qk_gemm.cu
  custom_ops/gpu_ops/moba_attn/moba_process/split_qkv_and_rope.cu
  custom_ops/setup_ops.py
  docs/features/moba_sparse_attention.md
  fastdeploy/config.py
  fastdeploy/engine/args_utils.py
  fastdeploy/engine/engine.py
  fastdeploy/model_executor/layers/attention/__init__.py
  fastdeploy/model_executor/layers/attention/attention.py
  fastdeploy/model_executor/layers/attention/moba_attention_backend.py
  fastdeploy/platforms/base.py
  fastdeploy/platforms/cuda.py
  fastdeploy/rl/rollout_config.py
  fastdeploy/worker/worker_process.py
  tests/layers/test_moba_attention.py
Labels: skip-ci: coverage

#3630 【CI case】for echo finish_reason text_after_process and raw_prediction check
  .github/workflows/_base_test.yml
  tests/ce/server/test_completions.py
  tests/ce/server/test_return_token_ids.py
  tools/codestyle/pre_commit.sh
Labels: contributor

#3624 【Bugfix】修复2.1分支上0.3B模型性能大幅下降
  fastdeploy/entrypoints/openai/serving_completion.py
  test/entrypoints/openai/test_completion_echo.py
Labels: contributor

#3646 Change paddlepaddle-xpu installation command
  scripts/run_ci_xpu.sh
Labels: contributor

#3655 [CI] add cleanup logic in release/2.1 workflows
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_unit_test_coverage.yml
  .github/workflows/ci_xpu.yml
Labels: contributor

#3581 [V1 Loader]support param create and load for wint2 and xpu backend
  fastdeploy/model_executor/layers/moe/check_backend_supported.py
  fastdeploy/model_executor/layers/moe/fused_moe_marlin_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_triton_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_wint2_backend.py
  fastdeploy/model_executor/layers/moe/fused_moe_xpu_backend.py
  fastdeploy/model_executor/layers/moe/moe.py
  fastdeploy/worker/gpu_model_runner.py
  fastdeploy/worker/metax_model_runner.py
  tests/ci_use/EB_VL_Lite/baseline.txt
Labels: skip-ci: coverage

#3578 【Hackathon 9th No.77】supplementary unit test for get_filtered_metrics
  tests/metrics/test_metrics.py
Labels: contributor, PaddlePaddle Hackathon

#3611 fix w4afp8_gemm_scale_permute import error on A100
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
Labels: skip-ci: coverage

#3159 Fix target_version
  pyproject.toml
Labels: contributor, HappyOpenSource

#3633 fix typos
  tests/operators/test_cutlass_scaled_mm.py
  tests/operators/test_w4afp8_gemm.py
  tests/operators/test_wfp8afp8_sparse_gemm.py
Labels: contributor, HappyOpenSource

#3690 Update _base_test.yml
  .github/workflows/_base_test.yml
Labels: contributor

#3675 [V1 Loader]Ernie mtp support loader v1
  fastdeploy/model_executor/layers/mtp_linear.py
  fastdeploy/model_executor/models/ernie4_5_mtp.py
Labels: skip-ci: coverage

#3580 【Hackathon 9th No.70】supplementary unit test for CPUPlatform and CUDAPlatform
  tests/platforms/test_platforms.py
Labels: contributor, PaddlePaddle Hackathon

#3311 [feat] completion api supports passing input token ids in either `prompt` or `prompt_token_ids`
  fastdeploy/entrypoints/openai/protocol.py
  fastdeploy/entrypoints/openai/serving_completion.py
  fastdeploy/input/ernie4_5_processor.py
  fastdeploy/input/text_processor.py
  tests/e2e/test_EB_Lite_serving.py
  tests/e2e/test_Qwen2-7B-Instruct_serving.py
Labels: contributor, skip-ci: coverage

#3680 [NewFeature] support w4afp8 eplb
  fastdeploy/model_executor/layers/moe/fused_moe_cutlass_backend.py
Labels: skip-ci: coverage

#3698 [CI] update paddle version to nightly
  .github/workflows/_accuracy_test.yml
  .github/workflows/_base_test.yml
  .github/workflows/_build_linux.yml
  .github/workflows/_logprob_test_linux.yml
  .github/workflows/_pre_ce_test.yml
  .github/workflows/_stable_test.yml
  .github/workflows/_unit_test_coverage.yml
  requirements.txt
  scripts/run_ci_xpu.sh
  scripts/run_unittest.sh
Labels: contributor

#3683 Optimize coverage jobs
  .github/workflows/_unit_test_coverage.yml
  scripts/.coveragerc
  scripts/coverage_run.sh
  tests/cov_pytest.ini
Labels: contributor

#3721 [Feature]support chat_template.jinja
  fastdeploy/entrypoints/chat_utils.py
  fastdeploy/entrypoints/llm.py
  fastdeploy/entrypoints/openai/api_server.py
Labels: contributor
